Repository bycza-zagroda/track-expenses-app-backend, pull requests merged in 2022-10, with the labels that each got.

#50 feature/48-update-githubwork-file
  docs/githubwork/GITHUB_WORK.md
  docs/githubwork/GITHUB_WORK.pl.md
  docs/githubwork/images/img003_create_branch.png
  docs/githubwork/images/img009_commits_message.png
Labels: documentation, 0.2 - Version

#55 bugfix/1-Discord-Link-Bug
  README.md
  README.pl.md
Labels: bug, 0.2 - Version

#57 bugfix/1-discord-link-bug
  pom.xml
Labels: bug, documentation, 0.2 - Version

#59 Feature/23 method to create single wallet
  src/main/java/pl/byczazagroda/trackexpensesappbackend/exception/GlobalExceptionHandlerController.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/exception/ResourceNotSavedException.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/service/WalletService.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/service/WalletServiceImpl.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/BaseControllerTestIT.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/controller/HelloWorldControllerTestIT.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/controller/WalletControllerTest.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/service/WalletServiceImplTest.java
Labels: 0.2 - Version, code-review

#60 Feature/28 a method that returns information about all wallets
  src/main/java/pl/byczazagroda/trackexpensesappbackend/controller/WalletController.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/exception/GlobalExceptionHandlerController.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/exception/ResourceNotFoundException.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/exception/WalletExceptionMessages.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/service/WalletService.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/service/WalletServiceImpl.java
  src/main/resources/application-test.yaml
  src/main/resources/db/changelog/003-create-table-wallet.yaml
  src/main/resources/db/dbchangelog-test.yaml
  src/test/java/pl/byczazagroda/trackexpensesappbackend/controller/WalletControllerTest.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/service/WalletServiceImplTest.java
Labels: 0.2 - Version

#53 Feature/24 modify single wallet
  src/main/java/pl/byczazagroda/trackexpensesappbackend/controller/WalletController.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/dto/UpdateWalletDTO.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/exception/GlobalExceptionHandlerController.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/exception/ResourceNotFoundException.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/exception/WalletExceptionHandler.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/model/Wallet.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/service/WalletService.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/service/WalletServiceImpl.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/BaseControllerTestIT.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/controller/WalletControllerTest.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/service/WalletServiceImplTest.java
Labels: 0.2 - Version

#44 feature/25 Add a method to delete a single wallet
  src/main/java/pl/byczazagroda/trackexpensesappbackend/controller/WalletController.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/exception/GlobalExceptionHandlerController.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/exception/ResourceNotDeletedException.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/exception/WalletExceptionHandler.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/exception/WalletNotDeletedException.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/service/WalletService.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/service/WalletServiceImpl.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/controller/WalletControllerTest.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/service/WalletServiceImplTest.java
Labels: 0.2 - Version
