Repository bycza-zagroda/track-expenses-app-backend, pull requests merged in 2023-01, with the labels that each got.

#102 Feature/as a user i want to find my transaction
  src/main/java/pl/byczazagroda/trackexpensesappbackend/controller/FinancialTransactionController.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/exception/ErrorCode.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/mapper/FinancialTransactionModelMapper.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/service/FinancialTransactionService.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/service/FinancialTransactionServiceImpl.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/service/FinancialTransactionServiceImplTest.java
Labels: enhancement, 0.3 - Version

#104 fix bug in application-xxx.yaml. bug 103 (github)
  src/main/resources/application-dev.yaml
  src/main/resources/application-prod.yaml
  src/main/resources/application-test.yaml
Labels: bug, 0.3 - Version

#105 refactor: rename ApiExceptionBase to ErrorResponse, and moved into pa…
  src/main/java/pl/byczazagroda/trackexpensesappbackend/controller/GlobalExceptionHandler.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/dto/error/DetailedErrorResponseImpl.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/dto/error/ErrorResponse.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/dto/error/ErrorResponseImpl.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/controller/WalletCreateControllerTest.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/controller/WalletDeleteControllerTest.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/controller/WalletGetControllerTest.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/controller/WalletUpdateControllerTest.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/service/FinancialTransactionServiceImplTest.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/service/WalletCreateServiceImplTest.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/service/WalletDeleteServiceImplTest.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/service/WalletGetServiceImplTest.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/service/WalletUpdateServiceImplTest.java
Labels: 0.3 - Version, refactoring

#109 Feature/implement find all financial transactions
  src/main/java/pl/byczazagroda/trackexpensesappbackend/controller/FinancialTransactionController.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/mapper/FinancialTransactionModelMapper.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/repository/FinancialTransactionRepository.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/service/FinancialTransactionService.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/service/FinancialTransactionServiceImpl.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/service/FinancialTransactionServiceImplTest.java
Labels: enhancement, 0.3 - Version

#112 Feature/as a user i want to add my transaction to my wallet
  src/main/java/pl/byczazagroda/trackexpensesappbackend/controller/FinancialTransactionController.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/controller/GlobalExceptionHandler.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/dto/CreateFinancialTransactionDTO.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/model/FinancialTransaction.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/service/FinancialTransactionService.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/service/FinancialTransactionServiceImpl.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/BaseIntegrationTestIT.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/service/FinancialTransactionServiceImplTest.java
Labels: enhancement, 0.3 - Version

#107 feature/ 75 As a user I want to change my transaction
  src/main/java/pl/byczazagroda/trackexpensesappbackend/controller/FinancialTransactionController.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/dto/UpdateFinancialTransactionDTO.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/exception/ErrorCode.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/model/FinancialTransaction.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/service/FinancialTransactionService.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/service/FinancialTransactionServiceImpl.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/service/FinancialTransactionServiceImplTest.java
Labels: enhancement, 0.3 - Version

#116 Feature/implement delete financial transaction
  src/main/java/pl/byczazagroda/trackexpensesappbackend/controller/FinancialTransactionController.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/service/FinancialTransactionService.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/service/FinancialTransactionServiceImpl.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/service/FinancialTransactionServiceImplTest.java
Labels: enhancement, 0.3 - Version
