Repository bycza-zagroda/track-expenses-app-backend, pull requests merged in 2023-08, with the labels that each got.

#286 Task create Financial Transaction Category
  src/main/java/pl/byczazagroda/trackexpensesappbackend/dto/FinancialTransactionCategoryCreateDTO.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/dto/FinancialTransactionCategoryUpdateDTO.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/service/FinancialTransactionCategoryServiceImpl.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/service/FinancialTransactionCategoryServiceImplTest.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/service/FinancialTransactionCategoryUpdateServiceImplTest.java
Labels: high, 0.5 - Version

#283 feature/248-implement user logout
  src/main/java/pl/byczazagroda/trackexpensesappbackend/config/WebSecurityConfig.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/controller/AuthController.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/service/UserService.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/service/UserServiceImpl.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/UserLogoutIT.java
Labels: 0.5 - Version

#288 fix validation of access token
  src/main/java/pl/byczazagroda/trackexpensesappbackend/service/UserService.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/service/UserServiceImpl.java
Labels: 0.5 - Version

#282 Create an integration tests for delete category endpoint
  src/main/java/pl/byczazagroda/trackexpensesappbackend/repository/FinancialTransactionCategoryRepository.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/service/FinancialTransactionCategoryServiceImpl.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/DeleteFinancialCategoryIT.java
Labels: integration test

#284 test: add FindFinancialTransactionCategoryIT class for test read by i…
  src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/FindFinancialTransactionCategoryIT.java
Labels: integration test, 0.5 - Version

#289 Create an integration tests for update category endpoint
  src/test/java/pl/byczazagroda/trackexpensesappbackend/BaseIntegrationTestIT.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/UpdateFinancialTransactionCategoryIT.java
Labels: integration test, 0.5 - Version

#280 Create an integration tests for create category endpoint. #262
  src/main/java/pl/byczazagroda/trackexpensesappbackend/controller/FinancialTransactionCategoryController.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/dto/FinancialTransactionCategoryCreateDTO.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/regex/RegexConstant.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/CreateFinancialTransactionCategoryIT.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/service/FinancialTransactionCategoryServiceImplTest.java
Labels: integration test, 0.5 - Version

#281 feat: fix test, update all wallet, add user #250
  src/main/java/pl/byczazagroda/trackexpensesappbackend/config/WebSecurityConfig.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/controller/WalletController.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/dto/WalletCreateDTO.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/exception/ErrorCode.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/mapper/WalletModelMapper.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/model/Wallet.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/repository/WalletRepository.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/service/WalletService.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/service/WalletServiceImpl.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/WalletTestIT.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/controller/WalletCreateControllerTest.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/controller/WalletDeleteControllerTest.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/controller/WalletGetControllerTest.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/controller/WalletUpdateControllerTest.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/CreateWalletIT.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/DeleteWalletByIdIT.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/FindAllWalletsByNameCaseSensitiveIT.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/FindTransactionByIDIT.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/FindWalletByIdIT.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/GetAllWalletsIT.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/UpdateWalletIT.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/service/FinancialTransactionServiceImplTest.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/service/WalletDeleteServiceImplTest.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/service/WalletGetServiceImplTest.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/service/WalletUpdateServiceImplTest.java
Labels: 0.5 - Version, liveCoding

#290 Add placeholder image
  docs/images/placeholder-150.png
Labels: documentation, enhancement
