Repository bycza-zagroda/track-expenses-app-backend, pull requests merged in 2023-06, with the labels that each got.

#252 feature/235-implement user registeration
  pom.xml
  src/main/java/pl/byczazagroda/trackexpensesappbackend/controller/AuthController.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/exception/ErrorCode.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/repository/UserRepository.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/service/UserService.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/service/UserServiceImpl.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/UserRegistrationIT.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/service/UserServiceImplTest.java
Labels: enhancement, 0.5 - Version

#259 reconfiguring the test container
  pom.xml
  src/test/java/pl/byczazagroda/trackexpensesappbackend/BaseIntegrationTestIT.java
Labels: 0.5 - Version

#266 Feature/238-association user and financial transaction category
  src/main/java/pl/byczazagroda/trackexpensesappbackend/model/FinancialTransactionCategory.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/model/User.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/service/FinancialTransactionCategoryServiceImpl.java
  src/main/resources/db/changelog/0003-create-table-financial_transaction_categories.yaml
  src/main/resources/db/changelog/0011-add-new-column-to-financial-transaction-category.yaml
  src/main/resources/db/changelog/0012-add-key-constraint-user-and-financial-transaction-category.yaml
  src/main/resources/db/changelog/data/financial_transaction_categories.csv
  src/main/resources/db/dbchangelog-dev.yaml
  src/main/resources/db/dbchangelog-prod.yaml
  src/main/resources/db/dbchangelog-test.yaml
  src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/CreateFinancialTransactionIT.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/UpdateTransactionByIdIT.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/service/FinancialTransactionCategoryServiceImplTest.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/service/FinancialTransactionServiceImplTest.java
Labels: 0.5 - Version

#260 Implement spring security config
  pom.xml
  src/main/java/pl/byczazagroda/trackexpensesappbackend/config/AppAccessDeniedHandler.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/config/AppAuthenticationEntryPoint.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/config/JwtAuthorizationFilter.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/config/WebSecurityConfig.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/controller/UserController.java
  src/main/resources/application-dev.yaml
  src/main/resources/application-prod.yaml
  src/main/resources/application-test.yaml
  src/main/resources/db/changelog/data/users.csv
  src/test/java/pl/byczazagroda/trackexpensesappbackend/WebSecurityConfigTest.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/controller/FinancialTransactionCategoryControllerTest.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/controller/WalletCreateControllerTest.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/controller/WalletDeleteControllerTest.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/controller/WalletGetControllerTest.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/controller/WalletUpdateControllerTest.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/CreateFinancialTransactionIT.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/CreateWalletIT.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/DeleteTransactionByIdIT.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/DeleteWalletByIdIT.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/FindAllWalletsByNameCaseSensitiveIT.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/FindTransactionByIDIT.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/FindWalletByIdIT.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/GetAllWalletsIT.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/GetFinancialTransactionByWalletIdIT.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/UpdateTransactionByIdIT.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/UpdateWalletIT.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/UserRegistrationIT.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/service/FinancialTransactionCategoryServiceImplTest.java
Labels: enhancement, high, 0.5 - Version

#261 Fix test case for finding wallets by name pattern and update repository methods (#251)
  src/main/java/pl/byczazagroda/trackexpensesappbackend/repository/WalletRepository.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/service/WalletServiceImpl.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/FindAllWalletsByNameCaseSensitiveIT.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/service/WalletGetServiceImplTest.java
Labels: 0.5 - Version

#269 256-update-financial-transaction-categry-DTO
  src/main/java/pl/byczazagroda/trackexpensesappbackend/dto/FinancialTransactionCategoryCreateDTO.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/dto/FinancialTransactionCategoryDTO.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/dto/FinancialTransactionCategoryUpdateDTO.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/exception/ErrorCode.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/mapper/FinancialTransactionCategoryModelMapper.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/service/FinancialTransactionCategoryServiceImpl.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/controller/FinancialTransactionCategoryControllerTest.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/service/FTCategoryUpdateServiceImplTest.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/service/FinancialTransactionCategoryServiceImplTest.java
Labels: 0.5 - Version

#272 Task/268 create a default application config
  src/main/resources/application-dev.yaml
  src/main/resources/application-prod.yaml
  src/main/resources/application-test.yaml
  src/main/resources/application.yaml
  src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/UserRegistrationIT.java
Labels: technical task, 0.5 - Version

#275 task/271-Implement error codes and DTO converter
  src/main/java/pl/byczazagroda/trackexpensesappbackend/config/AppAccessDeniedHandler.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/config/AppAuthenticationEntryPoint.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/config/WebSecurityConfig.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/exception/ErrorCode.java
Labels: enhancement, 0.5 - Version

#276 feat/Implemented user login
  src/main/java/pl/byczazagroda/trackexpensesappbackend/controller/AuthController.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/exception/ErrorCode.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/service/UserService.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/service/UserServiceImpl.java
  src/main/resources/application.yaml
  src/test/java/pl/byczazagroda/trackexpensesappbackend/controller/UserLoginTest.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/UserRegistrationIT.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/service/UserServiceImplTest.java
Labels: 0.5 - Version
