Repository bycza-zagroda/track-expenses-app-backend, pull requests merged in 2023-05, with the labels that each got.

#198 integration test for getting all Wallets
  src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/GetAllWalletsIT.java
Labels: 0.4 - Version

#226 bugfix/creating financial trasnaction
  src/main/java/pl/byczazagroda/trackexpensesappbackend/exception/ErrorCode.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/service/FinancialTransactionServiceImpl.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/CreateFinancialTransactionIT.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/service/FinancialTransactionServiceImplTest.java
Labels: bug, 0.4 - Version, unit test, integration test

#223 bugfix/update financial transaction
  src/main/java/pl/byczazagroda/trackexpensesappbackend/dto/FinancialTransactionUpdateDTO.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/service/FinancialTransactionServiceImpl.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/UpdateTransactionByIdIT.java
Labels: 0.4 - Version

#227 Bugfix/delete ft categry
  src/main/resources/db/changelog/008-add-onDelete-to-financial-transaction-foreignKey.yaml
  src/main/resources/db/dbchangelog-dev.yaml
  src/main/resources/db/dbchangelog-test.yaml
Labels: bug, 0.4 - Version

#243 technical_task/216-Create pull_request_template
  .github/pull_request_template.md
Labels: 0.4 - Version

#247 feature/242-draft_for_security_implementation
  src/main/java/pl/byczazagroda/trackexpensesappbackend/controller/AuthController.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/dto/AuthAccessTokenDTO.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/dto/AuthLoginDTO.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/dto/AuthRegisterDTO.java
Labels: 0.5 - Version

#241 feture: add user entity work at users table yaml
  src/main/java/pl/byczazagroda/trackexpensesappbackend/controller/WalletController.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/dto/UserDTO.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/dto/WalletCreateDTO.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/dto/WalletDTO.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/model/User.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/model/UserStatus.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/model/Wallet.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/repository/UserRepository.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/service/WalletService.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/service/WalletServiceImpl.java
  src/main/resources/db/changelog/0001-create-table-wallets.yaml
  src/main/resources/db/changelog/0002-create-table-financial_transactions.yaml
  src/main/resources/db/changelog/0003-create-table-financial_transaction_categories.yaml
  src/main/resources/db/changelog/0004-add-new-column-and-foreignKey-to-financial_transaction.yaml
  src/main/resources/db/changelog/0005-add-onDelete-to-financial-transaction-foreignKey.yaml
  src/main/resources/db/changelog/0006-add-constraints-on-columns-in-database-tables.sql
  src/main/resources/db/changelog/0006-add-constraints-on-columns-in-database-tables.yaml
  src/main/resources/db/changelog/0007-alter-table-wallets.yaml
  src/main/resources/db/changelog/0008-create-table-users.yaml
  src/main/resources/db/changelog/0009-add-constraints-foreign-key-wallets.yaml
  src/main/resources/db/changelog/0010-add-enum-user-status-check.sql
  src/main/resources/db/changelog/0010-add-enum-user-status-check.yaml
  src/main/resources/db/changelog/009-add-constraints-on-columns-in-database-tables.yaml
  src/main/resources/db/changelog/1001-insert-into-users.yaml
  src/main/resources/db/changelog/1002-insert-into-wallets.yaml
  src/main/resources/db/changelog/1003-insert-into-financial_transaction_categories.yaml
  src/main/resources/db/changelog/1004-insert-into-financial_transactions.yaml
  src/main/resources/db/changelog/data/users.csv
  src/main/resources/db/changelog/data/wallets.csv
  src/main/resources/db/dbchangelog-dev.yaml
  src/main/resources/db/dbchangelog-prod.yaml
  src/main/resources/db/dbchangelog-test.yaml
  src/test/java/pl/byczazagroda/trackexpensesappbackend/WalletTestIT.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/controller/WalletCreateControllerTest.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/controller/WalletDeleteControllerTest.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/controller/WalletGetControllerTest.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/controller/WalletUpdateControllerTest.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/CreateFinancialTransactionIT.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/CreateWalletIT.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/DeleteTransactionByIdIT.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/DeleteWalletByIdIT.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/FindAllWalletsByNameCaseSensitiveIT.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/FindTransactionByIDIT.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/FindWalletByIdIT.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/GetAllWalletsIT.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/GetFinancialTransactionByWalletIdIT.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/UpdateTransactionByIdIT.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/UpdateWalletIT.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/service/WalletCreateServiceImplTest.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/service/WalletGetServiceImplTest.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/service/WalletUpdateServiceImplTest.java
Labels: 0.5 - Version
