Repository bycza-zagroda/track-expenses-app-backend, pull requests merged in 2023-09, with the labels that each got.

#297 Feature/291 add security to financial transation
  src/main/java/pl/byczazagroda/trackexpensesappbackend/config/WebSecurityConfig.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/controller/FinancialTransactionCategoryController.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/controller/FinancialTransactionController.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/repository/FinancialTransactionRepository.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/repository/WalletRepository.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/service/FinancialTransactionCategoryServiceImpl.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/service/FinancialTransactionService.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/service/FinancialTransactionServiceImpl.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/CreateFinancialTransactionIT.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/DeleteTransactionByIdIT.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/GetFinancialTransactionByWalletIdIT.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/UpdateTransactionByIdIT.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/service/FinancialTransactionServiceImplTest.java
Labels: unit test, integration test, 0.5 - Version

#300 Version0.6.0
  pom.xml
  src/main/resources/application.yaml
Labels: 0.6 - Version

#299 feature/298 refactoring all application
  .run/Dev-TrackExpensesAppBackendApplication .run.xml
  .run/Dev-TrackExpensesAppBackendApplication.run.xml
  Dockerfile
  checkstyle/tea.xml
  src/main/java/pl/byczazagroda/trackexpensesappbackend/config/JwtAuthorizationFilter.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/controller/AuthController.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/controller/WalletController.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/dto/WalletCreateDTO.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/service/UserService.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/service/WalletServiceImpl.java
  src/main/resources/application-dev.yaml
  src/main/resources/application-prod.yaml
  src/main/resources/application-test.yaml
  src/main/resources/application.yaml
  src/main/resources/db/changelog/0001-create-table-wallets.yaml
  src/test/java/pl/byczazagroda/trackexpensesappbackend/WebSecurityConfigTest.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/DeleteWalletByIdIT.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/FindFinancialTransactionCategoryIT.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/FindTransactionByIDIT.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/FindWalletByIdIT.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/GetAllWalletsIT.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/UpdateFinancialTransactionCategoryIT.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/UpdateWalletIT.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/UserLogoutIT.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/UserRegistrationIT.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/service/FinancialTransactionCategoryUpdateServiceImplTest.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/service/UserServiceImplTest.java
Labels: 0.6 - Version

#301 Refactoring all application #298
  src/test/java/pl/byczazagroda/trackexpensesappbackend/service/FinancialTransactionServiceImplTest.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/service/WalletCreateServiceImplTest.java
Labels: refactoring, unit test, 0.6 - Version

#303 task/extend test utils class
  src/test/java/pl/byczazagroda/trackexpensesappbackend/IntegrationTestUtils.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/TestUtils.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/controller/FinancialTransactionCategoryControllerTest.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/controller/WalletDeleteControllerTest.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/controller/WalletGetControllerTest.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/controller/WalletUpdateControllerTest.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/CreateFinancialTransactionCategoryIT.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/CreateFinancialTransactionIT.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/CreateWalletIT.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/DeleteFinancialCategoryIT.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/DeleteTransactionByIdIT.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/DeleteWalletByIdIT.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/FindAllWalletsByNameCaseSensitiveIT.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/FindFinancialTransactionCategoryIT.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/FindTransactionByIDIT.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/FindWalletByIdIT.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/GetFinancialTransactionByWalletIdIT.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/RefreshTokenIT.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/UpdateFinancialTransactionCategoryIT.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/UpdateTransactionByIdIT.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/UpdateWalletIT.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/UserLogoutIT.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/service/FinancialTransactionCategoryServiceImplTest.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/service/FinancialTransactionCategoryUpdateServiceImplTest.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/service/FinancialTransactionServiceImplTest.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/service/UserServiceImplTest.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/service/WalletCreateServiceImplTest.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/service/WalletDeleteServiceImplTest.java
Labels: refactoring, technical task, unit test, integration test, 0.6 - Version

#306 Refactoring all application
  src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/FindAllWalletsByNameCaseSensitiveIT.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/UpdateTransactionByIdIT.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/service/FinancialTransactionCategoryServiceImplTest.java
Labels: refactoring, 0.6 - Version

#307 Refactoring app
  src/main/java/pl/byczazagroda/trackexpensesappbackend/auth/api/dto/AuthAccessTokenDTO.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/auth/api/dto/UserDTO.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/config/OpenApiConfig.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/financialTransaction/api/dto/FinancialTransactionCreateDTO.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/financialTransaction/api/dto/FinancialTransactionDTO.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/financialTransactionCategory/api/FinancialTransactionCategoryRepository.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/financialTransactionCategory/api/dto/FinancialTransactionCategoryDetailedDTO.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/financialTransactionCategory/api/model/FinancialTransactionCategory.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/general/exception/error/ErrorResponseDTO.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/general/exception/error/ErrorResponseDescriptionListDTO.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/wallet/api/model/Wallet.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/controller/UserLoginTest.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/DeleteWalletByIdIT.java
Labels: refactoring, 0.6 - Version
