Repository bycza-zagroda/track-expenses-app-backend, pull requests merged in 2023-03, with the labels that each got.

#158 Add DTO for category with FT counter
  src/main/java/pl/byczazagroda/trackexpensesappbackend/controller/FinancialTransactionCategoryController.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/dto/FinancialTransactionCategoryDetailedDTO.java
Labels: 0.4 - Version

#160 feat: Create FinancialTransactionCategory
  src/main/java/pl/byczazagroda/trackexpensesappbackend/model/FinancialTransactionCategory.java
Labels: 0.4 - Version

#156 Implement dbchangelog for financial transaction categories
  src/main/resources/db/changelog/005-create-table-financial_transaction_categories.yaml
  src/main/resources/db/changelog/006-insert-into-financial_transaction_categories.yaml
  src/main/resources/db/changelog/data/financial_transaction_categories.csv
  src/main/resources/db/changelog/data/financial_transactions.csv
  src/main/resources/db/dbchangelog-dev.yaml
  src/main/resources/db/dbchangelog-prod.yaml
Labels: 0.4 - Version

#167 refactor WalletController ~ deleteWalletById now return ResponseEntit…
  src/main/java/pl/byczazagroda/trackexpensesappbackend/controller/WalletController.java
Labels: bug, 0.4 - Version

#172 Feature/read all ft category implementation
  src/main/java/pl/byczazagroda/trackexpensesappbackend/controller/FinancialTransactionCategoryController.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/mapper/FinancialTransactionCategoryModelMapper.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/repository/FinancialTransactionCategoryRepository.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/service/FinancialTransactionCategoryService.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/service/FinancialTransactionCategoryServiceImpl.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/controller/FinancialTransactionCategoryControllerTest.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/service/FinancialTransactionCategoryServiceImplTest.java
Labels: enhancement, 0.4 - Version

#173 financial transaction category creation
  .run/Dev-TrackExpensesAppBackendApplication.run.xml
  .run/Prod-TrackExpensesAppBackendApplication.run.xml
  src/main/java/pl/byczazagroda/trackexpensesappbackend/controller/FinancialTransactionCategoryController.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/dto/FinancialTransactionCategoryCreateDTO.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/model/FinancialTransactionCategory.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/repository/FinancialTransactionCategoryRepository.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/repository/FinancialTransactionRepository.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/service/FinancialTransactionCategoryService.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/service/FinancialTransactionCategoryServiceImpl.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/service/FinancialTransactionCategoryServiceImplTest.java
Labels: enhancement, 0.4 - Version

#197 add: launch configuration files Dev-TrackExpensesAppBackendApplicatio…
  .run/Dev-TrackExpensesAppBackendApplication.run.xml
  .run/Prod-TrackExpensesAppBackendApplication.run.xml
Labels: technical task, high

#161 feature: update FT Category implementation #151
  src/main/java/pl/byczazagroda/trackexpensesappbackend/controller/FinancialTransactionCategoryController.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/exception/ErrorCode.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/mapper/FinancialTransactionCategoryModelMapper.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/model/FinancialTransactionCategory.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/repository/FinancialTransactionCategoryRepository.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/service/FinancialTransactionCategoryService.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/service/FinancialTransactionCategoryServiceImpl.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/service/FTCategoryUpdateServiceImplTest.java
Labels: 0.4 - Version
