Repository bycza-zagroda/track-expenses-app-backend, pull requests merged in 2023-02, with the labels that each got.

#130 refactor: Refactor method findById, checking for exceptions before ma…
  src/main/java/pl/byczazagroda/trackexpensesappbackend/service/FinancialTransactionServiceImpl.java
Labels: 0.3 - Version, refactoring

#136 Refactor/ FinancialTransactionServiceImpl updateTransaction method #119
  src/main/java/pl/byczazagroda/trackexpensesappbackend/controller/FinancialTransactionController.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/service/FinancialTransactionService.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/service/FinancialTransactionServiceImpl.java
Labels: code review, 0.3 - Version, refactoring

#118 refactor: refactor method getFinancialTransactionByWalletId in Financ…
  src/main/java/pl/byczazagroda/trackexpensesappbackend/service/FinancialTransactionServiceImpl.java
Labels: 0.3 - Version, refactoring, low

#121 refactor: Rename fields of the class FinancialTransaction
  src/main/java/pl/byczazagroda/trackexpensesappbackend/controller/FinancialTransactionController.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/controller/WalletController.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/dto/CreateFinancialTransactionDTO.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/dto/FinancialTransactionDTO.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/dto/UpdateFinancialTransactionDTO.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/model/FinancialTransaction.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/service/FinancialTransactionServiceImpl.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/service/FinancialTransactionServiceImplTest.java
Labels: 0.3 - Version, refactoring

#113 refactor: DefaultErrorStrategy
  src/main/java/pl/byczazagroda/trackexpensesappbackend/controller/GlobalExceptionHandler.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/controller/WalletController.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/dto/error/ErrorResponseDTO.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/dto/error/ErrorResponseDescriptionListDTO.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/exception/DefaultErrorStrategy.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/exception/DetailedErrorStrategy.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/exception/ErrorStrategy.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/service/FinancialTransactionServiceImpl.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/controller/WalletCreateControllerTest.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/controller/WalletDeleteControllerTest.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/controller/WalletGetControllerTest.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/controller/WalletUpdateControllerTest.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/service/FinancialTransactionServiceImplTest.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/service/WalletCreateServiceImplTest.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/service/WalletDeleteServiceImplTest.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/service/WalletGetServiceImplTest.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/service/WalletUpdateServiceImplTest.java
Labels: 0.3 - Version, refactoring

#138 refactor: Rename transactionDate to date
  src/main/java/pl/byczazagroda/trackexpensesappbackend/model/FinancialTransaction.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/repository/FinancialTransactionRepository.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/service/FinancialTransactionServiceImpl.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/service/FinancialTransactionServiceImplTest.java
Labels: 0.3 - Version, refactoring, high

#133 test: Add FinancialTransactionService unit tests
  src/test/java/pl/byczazagroda/trackexpensesappbackend/service/FinancialTransactionServiceImplTest.java
Labels: 0.3 - Version

#146 refactor of DTOs classes
  src/main/java/pl/byczazagroda/trackexpensesappbackend/controller/FinancialTransactionController.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/controller/WalletController.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/dto/FinancialTransactionCreateDTO.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/dto/FinancialTransactionUpdateDTO.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/dto/WalletCreateDTO.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/dto/WalletUpdateDTO.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/service/FinancialTransactionService.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/service/FinancialTransactionServiceImpl.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/service/WalletService.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/service/WalletServiceImpl.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/WalletTestIT.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/controller/WalletCreateControllerTest.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/controller/WalletUpdateControllerTest.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/service/FinancialTransactionServiceImplTest.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/service/WalletCreateServiceImplTest.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/service/WalletGetServiceImplTest.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/service/WalletUpdateServiceImplTest.java
Labels: refactoring, 0.4 - Version

#153 create draft for finacial transaction category
  src/main/java/pl/byczazagroda/trackexpensesappbackend/controller/FinancialTransactionCategoryController.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/dto/FinancialTransactionCategoryCreateDTO.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/dto/FinancialTransactionCategoryDTO.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/dto/FinancialTransactionCategoryUpdateDTO.java
Labels: 0.4 - Version, high
