Repository bycza-zagroda/track-expenses-app-backend, pull requests merged in 2023-04, with the labels that each got.

#199 integration test for update Wallet
  src/main/resources/db/dbchangelog-test.yaml
  src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/TestUpdateWallet.java
Labels: 0.4 - Version

#205 Feature/delete ft category implementation
  src/main/java/pl/byczazagroda/trackexpensesappbackend/controller/FinancialTransactionCategoryController.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/exception/ErrorCode.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/service/FinancialTransactionCategoryService.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/service/FinancialTransactionCategoryServiceImpl.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/service/FinancialTransactionCategoryServiceImplTest.java
Labels: 0.4 - Version

#204 Integration test for find transaction by Id
  src/main/resources/db/dbchangelog-test.yaml
  src/test/java/pl/byczazagroda/trackexpensesappbackend/BaseIntegrationTestIT.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/FindTransactionByIDTest.java
Labels: enhancement, 0.4 - Version

#186 test: integration test for get Financial Transactions By Wallet ID #183
  src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/GetFinancialTransactionByWalletIdIT.java
Labels: 0.4 - Version

#210 Integration test find wallet by ID
  src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/FindWalletByIdIT.java
Labels: 0.4 - Version

#194 Integration test for delete wallet by ID
  src/main/resources/db/dbchangelog-test.yaml
  src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/DeleteWalletByIdIT.java
Labels: 0.4 - Version

#220 test: integration test for update Transaction By ID #184
  src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/UpdateTransactionByIdIT.java
Labels: 0.4 - Version

#219 Bugfix/create financial transaction
  src/main/java/pl/byczazagroda/trackexpensesappbackend/dto/FinancialTransactionCreateDTO.java
  src/main/java/pl/byczazagroda/trackexpensesappbackend/service/FinancialTransactionServiceImpl.java
  src/test/java/pl/byczazagroda/trackexpensesappbackend/service/FinancialTransactionServiceImplTest.java
Labels: bug, 0.4 - Version
